/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivateRouteRouteImport } from './routes/_private/route'
import { Route as PrivateIndexRouteImport } from './routes/_private/index'
import { Route as PrivateSplatRouteImport } from './routes/_private/$'
import { Route as PublicApplicationsRouteRouteImport } from './routes/_public/applications/route'
import { Route as PublicApplicationsIndexRouteImport } from './routes/_public/applications/index'
import { Route as PrivateAdminsIndexRouteImport } from './routes/_private/admins/index'
import { Route as PublicApplicationsTeacherRouteImport } from './routes/_public/applications/teacher'

const PrivateRouteRoute = PrivateRouteRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateIndexRoute = PrivateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateSplatRoute = PrivateSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PublicApplicationsRouteRoute = PublicApplicationsRouteRouteImport.update({
  id: '/_public/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicApplicationsIndexRoute = PublicApplicationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicApplicationsRouteRoute,
} as any)
const PrivateAdminsIndexRoute = PrivateAdminsIndexRouteImport.update({
  id: '/admins/',
  path: '/admins/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PublicApplicationsTeacherRoute =
  PublicApplicationsTeacherRouteImport.update({
    id: '/teacher',
    path: '/teacher',
    getParentRoute: () => PublicApplicationsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PrivateIndexRoute
  '/applications': typeof PublicApplicationsRouteRouteWithChildren
  '/$': typeof PrivateSplatRoute
  '/applications/teacher': typeof PublicApplicationsTeacherRoute
  '/admins/': typeof PrivateAdminsIndexRoute
  '/applications/': typeof PublicApplicationsIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof PrivateSplatRoute
  '/': typeof PrivateIndexRoute
  '/applications/teacher': typeof PublicApplicationsTeacherRoute
  '/admins': typeof PrivateAdminsIndexRoute
  '/applications': typeof PublicApplicationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateRouteRouteWithChildren
  '/_public/applications': typeof PublicApplicationsRouteRouteWithChildren
  '/_private/$': typeof PrivateSplatRoute
  '/_private/': typeof PrivateIndexRoute
  '/_public/applications/teacher': typeof PublicApplicationsTeacherRoute
  '/_private/admins/': typeof PrivateAdminsIndexRoute
  '/_public/applications/': typeof PublicApplicationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/$'
    | '/applications/teacher'
    | '/admins/'
    | '/applications/'
  fileRoutesByTo: FileRoutesByTo
  to: '/$' | '/' | '/applications/teacher' | '/admins' | '/applications'
  id:
    | '__root__'
    | '/_private'
    | '/_public/applications'
    | '/_private/$'
    | '/_private/'
    | '/_public/applications/teacher'
    | '/_private/admins/'
    | '/_public/applications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateRouteRoute: typeof PrivateRouteRouteWithChildren
  PublicApplicationsRouteRoute: typeof PublicApplicationsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/': {
      id: '/_private/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PrivateIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/$': {
      id: '/_private/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof PrivateSplatRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_public/applications': {
      id: '/_public/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof PublicApplicationsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/applications/': {
      id: '/_public/applications/'
      path: '/'
      fullPath: '/applications/'
      preLoaderRoute: typeof PublicApplicationsIndexRouteImport
      parentRoute: typeof PublicApplicationsRouteRoute
    }
    '/_private/admins/': {
      id: '/_private/admins/'
      path: '/admins'
      fullPath: '/admins/'
      preLoaderRoute: typeof PrivateAdminsIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_public/applications/teacher': {
      id: '/_public/applications/teacher'
      path: '/teacher'
      fullPath: '/applications/teacher'
      preLoaderRoute: typeof PublicApplicationsTeacherRouteImport
      parentRoute: typeof PublicApplicationsRouteRoute
    }
  }
}

interface PrivateRouteRouteChildren {
  PrivateSplatRoute: typeof PrivateSplatRoute
  PrivateIndexRoute: typeof PrivateIndexRoute
  PrivateAdminsIndexRoute: typeof PrivateAdminsIndexRoute
}

const PrivateRouteRouteChildren: PrivateRouteRouteChildren = {
  PrivateSplatRoute: PrivateSplatRoute,
  PrivateIndexRoute: PrivateIndexRoute,
  PrivateAdminsIndexRoute: PrivateAdminsIndexRoute,
}

const PrivateRouteRouteWithChildren = PrivateRouteRoute._addFileChildren(
  PrivateRouteRouteChildren,
)

interface PublicApplicationsRouteRouteChildren {
  PublicApplicationsTeacherRoute: typeof PublicApplicationsTeacherRoute
  PublicApplicationsIndexRoute: typeof PublicApplicationsIndexRoute
}

const PublicApplicationsRouteRouteChildren: PublicApplicationsRouteRouteChildren =
  {
    PublicApplicationsTeacherRoute: PublicApplicationsTeacherRoute,
    PublicApplicationsIndexRoute: PublicApplicationsIndexRoute,
  }

const PublicApplicationsRouteRouteWithChildren =
  PublicApplicationsRouteRoute._addFileChildren(
    PublicApplicationsRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  PrivateRouteRoute: PrivateRouteRouteWithChildren,
  PublicApplicationsRouteRoute: PublicApplicationsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
