/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as PrivateRouteRouteImport } from './routes/_private/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PrivateProfileCompletionRouteImport } from './routes/_private/profile-completion'
import { Route as PrivateDashboardRouteImport } from './routes/_private/dashboard'
import { Route as PrivateSplatRouteImport } from './routes/_private/$'
import { Route as PublicApplicationsRouteRouteImport } from './routes/_public/applications/route'
import { Route as PublicApplicationsIndexRouteImport } from './routes/_public/applications/index'
import { Route as PublicVagasIdRouteImport } from './routes/_public/vagas.$id'
import { Route as PrivateAccountsProfileRouteImport } from './routes/_private/accounts/profile'
import { Route as PrivateAccountsApplicationsRouteImport } from './routes/_private/accounts/applications'
import { Route as PublicAuthRecoverAccountIndexRouteImport } from './routes/_public/_auth/recover-account/index'
import { Route as PublicAuthLoginIndexRouteImport } from './routes/_public/_auth/login/index'
import { Route as PublicAuthCreateAccountIndexRouteImport } from './routes/_public/_auth/create-account/index'
import { Route as PublicAuthResetPasswordTokenRouteImport } from './routes/_public/_auth/reset-password/$token'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRouteRoute = PrivateRouteRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PrivateProfileCompletionRoute =
  PrivateProfileCompletionRouteImport.update({
    id: '/profile-completion',
    path: '/profile-completion',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PrivateDashboardRoute = PrivateDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateSplatRoute = PrivateSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PublicApplicationsRouteRoute = PublicApplicationsRouteRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicApplicationsIndexRoute = PublicApplicationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicApplicationsRouteRoute,
} as any)
const PublicVagasIdRoute = PublicVagasIdRouteImport.update({
  id: '/vagas/$id',
  path: '/vagas/$id',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PrivateAccountsProfileRoute = PrivateAccountsProfileRouteImport.update({
  id: '/accounts/profile',
  path: '/accounts/profile',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateAccountsApplicationsRoute =
  PrivateAccountsApplicationsRouteImport.update({
    id: '/accounts/applications',
    path: '/accounts/applications',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PublicAuthRecoverAccountIndexRoute =
  PublicAuthRecoverAccountIndexRouteImport.update({
    id: '/_auth/recover-account/',
    path: '/recover-account/',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const PublicAuthLoginIndexRoute = PublicAuthLoginIndexRouteImport.update({
  id: '/_auth/login/',
  path: '/login/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicAuthCreateAccountIndexRoute =
  PublicAuthCreateAccountIndexRouteImport.update({
    id: '/_auth/create-account/',
    path: '/create-account/',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const PublicAuthResetPasswordTokenRoute =
  PublicAuthResetPasswordTokenRouteImport.update({
    id: '/_auth/reset-password/$token',
    path: '/reset-password/$token',
    getParentRoute: () => PublicRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/applications': typeof PublicApplicationsRouteRouteWithChildren
  '/$': typeof PrivateSplatRoute
  '/dashboard': typeof PrivateDashboardRoute
  '/profile-completion': typeof PrivateProfileCompletionRoute
  '/accounts/applications': typeof PrivateAccountsApplicationsRoute
  '/accounts/profile': typeof PrivateAccountsProfileRoute
  '/vagas/$id': typeof PublicVagasIdRoute
  '/applications/': typeof PublicApplicationsIndexRoute
  '/reset-password/$token': typeof PublicAuthResetPasswordTokenRoute
  '/create-account/': typeof PublicAuthCreateAccountIndexRoute
  '/login/': typeof PublicAuthLoginIndexRoute
  '/recover-account/': typeof PublicAuthRecoverAccountIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/$': typeof PrivateSplatRoute
  '/dashboard': typeof PrivateDashboardRoute
  '/profile-completion': typeof PrivateProfileCompletionRoute
  '/accounts/applications': typeof PrivateAccountsApplicationsRoute
  '/accounts/profile': typeof PrivateAccountsProfileRoute
  '/vagas/$id': typeof PublicVagasIdRoute
  '/applications': typeof PublicApplicationsIndexRoute
  '/reset-password/$token': typeof PublicAuthResetPasswordTokenRoute
  '/create-account': typeof PublicAuthCreateAccountIndexRoute
  '/login': typeof PublicAuthLoginIndexRoute
  '/recover-account': typeof PublicAuthRecoverAccountIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_public/applications': typeof PublicApplicationsRouteRouteWithChildren
  '/_private/$': typeof PrivateSplatRoute
  '/_private/dashboard': typeof PrivateDashboardRoute
  '/_private/profile-completion': typeof PrivateProfileCompletionRoute
  '/_public/': typeof PublicIndexRoute
  '/_private/accounts/applications': typeof PrivateAccountsApplicationsRoute
  '/_private/accounts/profile': typeof PrivateAccountsProfileRoute
  '/_public/vagas/$id': typeof PublicVagasIdRoute
  '/_public/applications/': typeof PublicApplicationsIndexRoute
  '/_public/_auth/reset-password/$token': typeof PublicAuthResetPasswordTokenRoute
  '/_public/_auth/create-account/': typeof PublicAuthCreateAccountIndexRoute
  '/_public/_auth/login/': typeof PublicAuthLoginIndexRoute
  '/_public/_auth/recover-account/': typeof PublicAuthRecoverAccountIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/$'
    | '/dashboard'
    | '/profile-completion'
    | '/accounts/applications'
    | '/accounts/profile'
    | '/vagas/$id'
    | '/applications/'
    | '/reset-password/$token'
    | '/create-account/'
    | '/login/'
    | '/recover-account/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/dashboard'
    | '/profile-completion'
    | '/accounts/applications'
    | '/accounts/profile'
    | '/vagas/$id'
    | '/applications'
    | '/reset-password/$token'
    | '/create-account'
    | '/login'
    | '/recover-account'
  id:
    | '__root__'
    | '/_private'
    | '/_public'
    | '/_public/applications'
    | '/_private/$'
    | '/_private/dashboard'
    | '/_private/profile-completion'
    | '/_public/'
    | '/_private/accounts/applications'
    | '/_private/accounts/profile'
    | '/_public/vagas/$id'
    | '/_public/applications/'
    | '/_public/_auth/reset-password/$token'
    | '/_public/_auth/create-account/'
    | '/_public/_auth/login/'
    | '/_public/_auth/recover-account/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateRouteRoute: typeof PrivateRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_private/profile-completion': {
      id: '/_private/profile-completion'
      path: '/profile-completion'
      fullPath: '/profile-completion'
      preLoaderRoute: typeof PrivateProfileCompletionRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/dashboard': {
      id: '/_private/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PrivateDashboardRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/$': {
      id: '/_private/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof PrivateSplatRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_public/applications': {
      id: '/_public/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof PublicApplicationsRouteRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/applications/': {
      id: '/_public/applications/'
      path: '/'
      fullPath: '/applications/'
      preLoaderRoute: typeof PublicApplicationsIndexRouteImport
      parentRoute: typeof PublicApplicationsRouteRoute
    }
    '/_public/vagas/$id': {
      id: '/_public/vagas/$id'
      path: '/vagas/$id'
      fullPath: '/vagas/$id'
      preLoaderRoute: typeof PublicVagasIdRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_private/accounts/profile': {
      id: '/_private/accounts/profile'
      path: '/accounts/profile'
      fullPath: '/accounts/profile'
      preLoaderRoute: typeof PrivateAccountsProfileRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/accounts/applications': {
      id: '/_private/accounts/applications'
      path: '/accounts/applications'
      fullPath: '/accounts/applications'
      preLoaderRoute: typeof PrivateAccountsApplicationsRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_public/_auth/recover-account/': {
      id: '/_public/_auth/recover-account/'
      path: '/recover-account'
      fullPath: '/recover-account/'
      preLoaderRoute: typeof PublicAuthRecoverAccountIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_auth/login/': {
      id: '/_public/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof PublicAuthLoginIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_auth/create-account/': {
      id: '/_public/_auth/create-account/'
      path: '/create-account'
      fullPath: '/create-account/'
      preLoaderRoute: typeof PublicAuthCreateAccountIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_auth/reset-password/$token': {
      id: '/_public/_auth/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof PublicAuthResetPasswordTokenRouteImport
      parentRoute: typeof PublicRouteRoute
    }
  }
}

interface PrivateRouteRouteChildren {
  PrivateSplatRoute: typeof PrivateSplatRoute
  PrivateDashboardRoute: typeof PrivateDashboardRoute
  PrivateProfileCompletionRoute: typeof PrivateProfileCompletionRoute
  PrivateAccountsApplicationsRoute: typeof PrivateAccountsApplicationsRoute
  PrivateAccountsProfileRoute: typeof PrivateAccountsProfileRoute
}

const PrivateRouteRouteChildren: PrivateRouteRouteChildren = {
  PrivateSplatRoute: PrivateSplatRoute,
  PrivateDashboardRoute: PrivateDashboardRoute,
  PrivateProfileCompletionRoute: PrivateProfileCompletionRoute,
  PrivateAccountsApplicationsRoute: PrivateAccountsApplicationsRoute,
  PrivateAccountsProfileRoute: PrivateAccountsProfileRoute,
}

const PrivateRouteRouteWithChildren = PrivateRouteRoute._addFileChildren(
  PrivateRouteRouteChildren,
)

interface PublicApplicationsRouteRouteChildren {
  PublicApplicationsIndexRoute: typeof PublicApplicationsIndexRoute
}

const PublicApplicationsRouteRouteChildren: PublicApplicationsRouteRouteChildren =
  {
    PublicApplicationsIndexRoute: PublicApplicationsIndexRoute,
  }

const PublicApplicationsRouteRouteWithChildren =
  PublicApplicationsRouteRoute._addFileChildren(
    PublicApplicationsRouteRouteChildren,
  )

interface PublicRouteRouteChildren {
  PublicApplicationsRouteRoute: typeof PublicApplicationsRouteRouteWithChildren
  PublicIndexRoute: typeof PublicIndexRoute
  PublicVagasIdRoute: typeof PublicVagasIdRoute
  PublicAuthResetPasswordTokenRoute: typeof PublicAuthResetPasswordTokenRoute
  PublicAuthCreateAccountIndexRoute: typeof PublicAuthCreateAccountIndexRoute
  PublicAuthLoginIndexRoute: typeof PublicAuthLoginIndexRoute
  PublicAuthRecoverAccountIndexRoute: typeof PublicAuthRecoverAccountIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicApplicationsRouteRoute: PublicApplicationsRouteRouteWithChildren,
  PublicIndexRoute: PublicIndexRoute,
  PublicVagasIdRoute: PublicVagasIdRoute,
  PublicAuthResetPasswordTokenRoute: PublicAuthResetPasswordTokenRoute,
  PublicAuthCreateAccountIndexRoute: PublicAuthCreateAccountIndexRoute,
  PublicAuthLoginIndexRoute: PublicAuthLoginIndexRoute,
  PublicAuthRecoverAccountIndexRoute: PublicAuthRecoverAccountIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PrivateRouteRoute: PrivateRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
